---

- name: Get Plugins
  get_url: url={{ nagios_pluginsurl }} dest={{ nagios_download_dir }}/{{ nagios_pluginssrc }}.tar.gz

- name: Unpack Plugin source files
  shell: cd {{ nagios_download_dir }} && tar -xzvf {{ nagios_pluginssrc }}.tar.gz

- name: Configure Plugins
  shell: cd {{ nagios_download_dir }}/{{ nagios_pluginssrc }} && ./configure --with-nagios-user={{ nagios_monitoring_user }} --with-nagios-group=nagios --with-openssl

- name: Make Plugins
  shell: cd {{ nagios_download_dir }}/{{ nagios_pluginssrc }} && make

- name: Make Install Plugins
  shell: cd {{ nagios_download_dir }}/{{ nagios_pluginssrc }} && make install
