---
- name: install Dovecot
  package:
    name: dovecot
    state: latest

- name: ensure Dovecot is started and runs at startup
  service:
    name: dovecot
    state: started
    enabled: yes

- name: configure Dovecot (dovecot.conf)
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
  notify: restart dovecot

- name: configure Dovecot (10-mail.conf)
  template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
  notify: restart dovecot

- name: configure Dovecot (10-auth.conf)
  template:
    src: 10-auth.conf.j2
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
  notify: restart dovecot



