---
- name: remove default sendmail 
  package: 
    name: sendmail
    state: absent

- name: install Postfix
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - postfix
    - telnet
    - mailx

- name: ensure Postfix is started and runs at startup
  service:
    name: postfix
    state: started
    enabled: yes

- name: configure Postfix (main.cf)
  template:
    src: postfix_main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix



