---

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ phpldapadmin_packages }}"

- name: Copy config.php templates
  template:
    src: config.php.j2
    dest: /etc/phpldapadmin/config.php

- name: Copy phpldapadmin.conf templates
  template:
    src: phpldapadmin.conf.j2
    dest: /etc/httpd/conf.d/phpldapadmin.conf
  notify: restart apache




