---

- name: packeges need to be installed on all VMs
  hosts: all
  become: yes
  remote_user: ansible
  tasks: 
    - name: install packages
      package: 
        name: "{{ packages }}"
        state: installed
      with_items: 
        - bind-utils
        - man-db
        - man-pages 
        - mlocate
        - sysstat

