---

- name: install nfs packages for centos7
  package: 
    name: "{{ item }}"
    state: latest
  with_items: 
    - nfs-utils
  when:    
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "CentOS"

- name: start the services
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: 
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap
  
- name: create mountable dir 
  file: path=/share state=directory mode=777 owner=nfsnobody group=nfsnobody

- name: modify /etc/exports file 
  template: src=exports.j2 dest=/etc/exports
  notify: update nfs exports

- name: update nfs exports
  command: "exportfs -av"

- name: ensure firewalld is disable
  firewalld: service=firewalld state=disabled permanent=yes
  notify: restart nfs


